### ISSUE TITLE
Restrict strings for atomic symbols 

### ISSUE THREAD

**Issue by marcofavorito** [whitemech/flloat#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Consider restricting the set of possible strings for atomic symbols, similar to what is done by 
[SPOT](https://spot.lrde.epita.fr/tl.pdf), Section 2.2.

**Describe alternatives you've considered**

**Additional context**

**Comment by cipollone** [comment]
Does this issue refers to the atomic symbols in all logics?
I can implement the least restrictive constraint in the base class, such as: "any word or any quoted string", in a regular expression. Then each logic can add its own constraint, if needed. I can do this after reviewing LDLf parsing.

**Comment by cipollone** [comment]
Solved in #20
