### ISSUE TITLE
Implies formula evaluation does not work correctly.

### ISSUE THREAD

**Issue by marcofavorito** [whitemech/flloat#14]
### Subject of the issue

It seems the truth evaluation of `*Implies` formulas does not work correctly (see [here](https://github.com/whitemech/flloat/pull/11#issuecomment-592672667) for an example).

### Your environment
- OS: N/A
- Python version: N/A
- Package Version: N/A (the issue is on `develop`).

**Comment by cipollone** [comment]
Is this an intended behaviour, as of #16 ?
