### ISSUE TITLE
FunctionSymbol and PredicateSymbol class issue

### ISSUE THREAD

**Issue by aadeshnpn** [whitemech/flloat#2]
* FLLOAT version: 0.1.4.post1
* Python version: 3.6.0
* Operating System: Ubuntu

### Description

I want to create object of `FunctionSymbol` but I think the class definition is wrong so I can't initialize it. 

### What I Did
```
from flloat.base.Symbol import FunctionSymbol
>>> symbol = FunctionSymbol('A', 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: str() argument 2 must be str, not int
```
Now matter what argument you pass, object of this class won't be created. The same is true for PredicateSymbol.

**Comment by cipollone** [comment]
I think we can close this @marcofavorito , as this is no longer relevant both for the current master version (v0.2.3) and for the current develop version.
