### ISSUE TITLE
Documentation example for LTLF not working

### ISSUE THREAD

**Issue by aadeshnpn** [whitemech/flloat#31]
### Subject of the issue
I just copied this code from documentation. But it throws the error
![image](https://user-images.githubusercontent.com/1760420/89601161-dc586880-d831-11ea-8742-9e5c7f9eb49a.png)

`
from flloat.parser.ltlf import LTLfParser

parser = LTLfParser()
formula = "F (A & !B)"
parsed_formula = parser(formula)
t1 = [
    {"A": False, "B": False},
    {"A": True, "B": False},
    {"A": True, "B": False},
    {"A": True, "B": True},
    {"A": False, "B": False},
]
assert parsed_formula.truth(t1, 0)
t2 = [
    {"A": False, "B": False},
    {"A": True, "B": True},
    {"A": False, "B": True},
]
assert not parsed_formula.truth(t2, 0)
dfa = parsed_formula.to_automaton()
assert dfa.accepts(t1)
assert not dfa.accepts(t2)
`

### Your environment
- OS: Ubuntu
- Python version: 3.6
- Package Version 0.3.0

**Comment by cipollone** [comment]
You're right, the example is not up to date.

In the current version, atoms cannot start with upper-case letters. This is to avoid confusion with LTL temporal operators.

Hope this helps.

**Comment by aadeshnpn** [comment]
Thanks @cipollone. Yeah. I figured out that after I posted this issue. I can update the example and send you a pull request if that works.

**Comment by cipollone** [comment]
Actually, now I see that this was corrected at the very next commit: 75e8ec9.
We just didn't publish the latest version because we're not currently working on it.

Thanks!
